version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'sharebooks'
       MYSQL_USER: 'sb'
       MYSQL_PASSWORD: 'shareB00KS'
       MYSQL_ROOT_PASSWORD: 'root'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8990
    volumes:
      - .:/code
    ports:
      - "8990:8990"
    depends_on:
      - db
